vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        media_objects:
            uri_prefix: /images/media_objects
            upload_destination: '%kernel.project_dir%/public/images/media_objects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
